Editable FP Registers
SWIM-ucf/SWIM pull request #351
Opened 2024-03-01 22:09 UTC by cayb0rg

Will work after merging in #349 which sends the `UpdateCoprocessor` message from the emulator core

* Adds editable FP registers
* Adds new FPRegisters struct similar to GPRegisters
  * This abstracts away a few of the tasks required by the UI (such as checking valid register values)
 * Compresses reg view functions into one for gpr and one for fpr

2024-03-02 00:05 UTC, brooksmckinley requested changes
Amazing PR! All I really have are small simplifications and nitpicks.

2024-03-02 00:05 UTC, brooksmckinley commented on src/emulation_core/mips/line_info.rs
> +pub fn visual_line_to_data(
This seems identical to the implementation in visual_datapath/utils.rs, can one of them be removed?

2024-03-02 00:05 UTC, brooksmckinley commented on src/emulation_core/mips/datapath.rs
> +        let register = &mut self.coprocessor.registers[_register];
This one's probably my fault from when I wrote the datapath trait, but can we remove the underscores in the argument names? I used them back in the datapath trait when I was writing to turn off the unused variable warnings, but they're not really needed anymore. There's a few other places in this PR that have underscored arguments that end up getting used too.

2024-03-02 00:22 UTC, cayb0rg commented
Thank you for the feedback!

2024-03-06 20:02 UTC, brooksmckinley approved these changes
LGTM, ready to merge if you are.

2024-03-07 13:30 UTC, merged